"use client";

import React from "react";
import Image from "next/image";
import { Typography} from "@material-tailwind/react";


export function MobileConvenience() {
  return (
    <section className="py-20 px-8">
      <h2 className="font-bold text-5xl mt-5 tracking-tight text-center" ></h2>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 max-w-6xl mx-auto items-center">
        <Image
          width={256}
          height={256}
          src="/image/bannerscreatives.png"
          className="col-span-1 w-1/2 mx-auto lg:w-10/12 p-20"
          alt="iphone-photo"
        />
        <div className="col-span-1 mx-auto max-w-lg px-4 lg:px-0">
          <Typography placeholder="" variant="h2" color="blue-gray" className="mb-4">
          Free Banners/Creatives
          </Typography>
          <Typography
          placeholder=""
            variant="lead"
            className="mb-5 px-4 text-left  text-xl !text-gray-500 lg:px-0  "
          >
            TapGro makes it super easy to create attractive banners for your beauty business. Our automated designs are generated by the system, saving you time and effort, so you can promote your services in style and attract more clients!
          </Typography>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 max-w-6xl mx-auto items-center">
        <div className="col-span-1 mx-auto max-w-lg px-4 lg:px-0">
          <Typography placeholder="" variant="h2" color="blue-gray" className="mb-4">
          One click WhatsApp Marketing
          </Typography>
          <Typography
          placeholder=""
            variant="lead"
            className="mb-5 px-4 text-left text-xl !text-gray-500 lg:px-0"
          >
            TapGro simplifies WhatsApp marketing for your beauty business. With just one click, you can send messages to over 100 people without worrying about getting blocked, making client communication efficient and hassle-free.
          </Typography>
        </div>
        <Image
          width={256}
          height={256}
          src="/image/whatsapp.png"
          className="col-span-1 w-1/2 mx-auto lg:w-10/12 p-20 order-first lg:order-none"
          alt="iphone-photo"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 max-w-6xl mx-auto items-center">
        <Image
          width={256}
          height={256}
          src="/image/Automated.png"
          className="col-span-1 w-1/2 mx-auto lg:w-10/12 p-20"
          alt="Automated"
        />
        <div className="col-span-1 mx-auto max-w-lg px-4 lg:px-0">
          <Typography placeholder="" variant="h2" color="blue-gray" className="mb-4">
          Automated Reminders
          </Typography>
          <Typography
          placeholder=""
            variant="lead"
            className="mb-5 px-4 text-left  text-xl !text-gray-500 lg:px-0  "
          >
           TapGro takes care of your clients with automatic reminders. Never miss an appointment—our system sends friendly reminders for services, making sure your customers stay informed and engaged effortlessly.
          </Typography>
        </div>
      </div>
    </section>
  );
}
export default MobileConvenience;
