
"use client"
// Import necessary libraries and components
import React from 'react';
import {
  Tabs,
  TabsHeader,
  TabsBody,
  Tab,
  TabPanel,
} from "@material-tailwind/react";
import Image from "next/image";

export function MobileTabs() {
  const data = [
    {
      label: "Free Banners/Creatives",
      value: "html",
      Image: <Image width={200} height={200} src="/image/bannerscreatives.png" alt="iphone-photo" />,
      desc: 'TapGro makes it super easy to create attractive banners for your beauty business. Our automated designs are generated by the system, saving you time and effort, so you can promote your services in style and attract more clients!'
    },
    {
      label: "One click WhatsApp Marketing",
      value: "react",
      Image: <Image width={200} height={200} src="/image/whatsapp.png" alt="iphone-photo" />,
      desc: 'TapGro simplifies WhatsApp marketing for your beauty business. With just one click, you can send messages to over 100 people without worrying about getting blocked, making client communication efficient and hassle-free.'
    },
    {
      label: "Automated Reminders",
      value: "vue",
      Image: <Image width={200} height={200} src="/image/Automated.png" alt="iphone-photo" />,
      desc: 'TapGro takes care of your clients with automatic reminders. Never miss an appointment—our system sends friendly reminders for services, making sure your customers stay informed and engaged effortlessly.'
    },
  ];

  return (
    <div className="container mx-auto mt-32 grid h-full w-full grid-cols-1 place-items-center">
      <Tabs orientation="vertical">
        <TabsHeader placeholder="YourPlaceholderValue">
          {data.map(({ label, value }) => (
            <Tab placeholder="YourPlaceholderValue" className="h-40" key={value} value={value}>
              {label}
            </Tab>
          ))}
        </TabsHeader>
        <TabsBody>
          
          {data.map(({ value, Image ,desc }) => (
            <TabPanel key={value} value={value} className="py-0">
              {Image}
              {desc}
            </TabPanel>
          ))}
        </TabsBody>
      </Tabs>
    </div>
  );
}
