"use client";

import React from "react";
import Image from "next/image";
import { Typography} from "@material-tailwind/react";


export function MobileConvenience() {
  return (
    <section className="py-20 px-8">
      <h2 className="font-bold text-5xl mt-5 tracking-tight text-center">But Also,</h2>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 max-w-6xl mx-auto items-center">
        <Image
          width={256}
          height={256}
          src="/image/bannerscreatives.png"
          className="col-span-1 w-1/2 mx-auto lg:w-10/12 p-20"
          alt="iphone-photo"
        />
        <div className="col-span-1 mx-auto max-w-lg px-4 lg:px-0">
          <Typography placeholder="" variant="h2" color="orange" className="mb-4">
          Free Banners/Creatives
          </Typography>
          <Typography
          placeholder=""
            variant="lead"
            className="mb-3 px-4 text-left text-2xl text-slate-950 lg:px-0 font-sans lg:font-serif"
          >
            TapGro makes it super easy to create attractive banners for your beauty business. <span className="font-bold" style={{color:"#2035E5"}}> Our automated designs are generated by the system, saving you time and effort,</span> so you can promote your services in style and attract more clients!
          </Typography>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 max-w-6xl mx-auto items-center">
        <div className="col-span-1 mx-auto max-w-lg px-4 lg:px-0">
          <Typography placeholder="" variant="h2" color="blue-gray" className="mb-4">
          One click WhatsApp Marketing
          </Typography>
          <Typography
          placeholder=""
            variant="lead"
            className="mb-3 px-4 text-left text-2xl text-slate-950 lg:px-0"
          >
            TapGro simplifies WhatsApp marketing for your beauty business. <span className="font-bold" style={{color:'#28E50A'}}> With just one click, you can send messages to over 100 people</span> without worrying about getting blocked, making client communication efficient and hassle-free.
          </Typography>
        </div>
        <Image
          width={256}
          height={256}
          src="/image/whatsapp.png"
          className="col-span-1 w-1/2 mx-auto lg:w-10/12 p-20 order-first lg:order-none"
          alt="iphone-photo"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 max-w-6xl mx-auto items-center">
        <Image
          width={256}
          height={256}
          src="/image/Automated.png"
          className="col-span-1 w-1/2 mx-auto lg:w-10/12 p-20"
          alt="Automated"
        />
        <div className="col-span-1 mx-auto max-w-lg px-4 lg:px-0">
          <Typography placeholder="" variant="h2" color="blue-gray" className="mb-4">
          Automated Reminders
          </Typography>
          <Typography
          placeholder=""
            variant="lead"
            className="mb-3 px-4 text-left text-2xl text-slate-950 lg:px-0  "
          >
           TapGro takes care of your clients with automatic reminders. <span className="font-bold" style={{color:'#E50AC7'}}>Never miss an appointment—our system sends friendly reminders for services </span>, making sure your customers stay informed and engaged effortlessly.
          </Typography>
        </div>
      </div>
      <h2 className="font-bold text-5xl mt-5 tracking-tight text-center">Exclusively on TapGro...!!</h2>
    </section>
  );
}
export default MobileConvenience;
